def create_sample_shoes():
    """Crea zapatillas de ejemplo deportivas especializadas con género"""
    sample_shoes = [
        # ==================== HOMBRES - ROAD RUNNING NEUTRO/SUPINACIÓN ====================
        {
            'brand': 'Nike',
            'model': 'Pegasus 41',
            'category': 'running',
            'price': 129.99,
            'image_url': 'https://images.unsplash.com/photo-1605348532760-6753d2c43329?w=400',
            'affiliate_link': '#',
            'width_fit': 'standard',
            'arch_support': 'neutral',
            'weight_capacity': 'medium',
            'best_for_activity': 'road_running',
            'cushioning': 'medium',
            'footstrike_support': 'neutral',
            'distance_capacity': 'long',
            'carbon_plate': False,
            'best_for_distance': 'training',
            'gender': 'male'
        },
        {
            'brand': 'ASICS',
            'model': 'Novablast 5',
            'category': 'running',
            'price': 139.99,
            'image_url': 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=400',
            'affiliate_link': '#',
            'width_fit': 'wide',
            'arch_support': 'neutral',
            'weight_capacity': 'medium',
            'best_for_activity': 'road_running',
            'cushioning': 'maximum',
            'footstrike_support': 'neutral',
            'distance_capacity': 'long',
            'carbon_plate': False,
            'best_for_distance': 'training',
            'gender': 'male'
        },
        {
            'brand': 'Brooks',
            'model': 'Ghost 17',
            'category': 'running',
            'price': 139.99,
            'image_url': 'https://images.unsplash.com/photo-1600185365483-26d7a4cc7519?w=400',
            'affiliate_link': '#',
            'width_fit': 'standard',
            'arch_support': 'neutral',
            'weight_capacity': 'medium',
            'best_for_activity': 'road_running',
            'cushioning': 'maximum',
            'footstrike_support': 'neutral',
            'distance_capacity': 'long',
            'carbon_plate': False,
            'best_for_distance': 'training',
            'gender': 'male'
        },
        {
            'brand': 'Adidas',
            'model': 'Adizero Evo SL',
            'category': 'running',
            'price': 169.99,
            'image_url': 'https://images.unsplash.com/photo-1549298916-b41d501d3772?w=400',
            'affiliate_link': '#',
            'width_fit': 'narrow',
            'arch_support': 'neutral',
            'weight_capacity': 'light',
            'best_for_activity': 'road_running',
            'cushioning': 'medium',
            'footstrike_support': 'neutral',
            'distance_capacity': 'medium',
            'carbon_plate': False,
            'best_for_distance': 'training',
            'gender': 'male'
        },
        {
            'brand': 'Mizuno',
            'model': 'Neo Vista 2',
            'category': 'running',
            'price': 179.99,
            'image_url': 'https://images.unsplash.com/photo-1600185365483-26d7a4cc7519?w=400',
            'affiliate_link': '#',
            'width_fit': 'standard',
            'arch_support': 'neutral',
            'weight_capacity': 'medium',
            'best_for_activity': 'road_running',
            'cushioning': 'maximum',
            'footstrike_support': 'neutral',
            'distance_capacity': 'long',
            'carbon_plate': False,
            'best_for_distance': 'long_run',
            'gender': 'male'
        },
        {
            'brand': 'Under Armour',
            'model': 'Sonic 7',
            'category': 'running',
            'price': 99.99,
            'image_url': 'https://images.unsplash.com/photo-1549298916-b41d501d3772?w=400',
            'affiliate_link': '#',
            'width_fit': 'standard',
            'arch_support': 'neutral',
            'weight_capacity': 'light',
            'best_for_activity': 'road_running',
            'cushioning': 'medium',
            'footstrike_support': 'neutral',
            'distance_capacity': 'medium',
            'carbon_plate': False,
            'best_for_distance': 'training',
            'gender': 'male'
        },
        # ==================== MUJERES - ROAD RUNNING NEUTRO/SUPINACIÓN ====================
        {
            'brand': 'Hoka',
            'model': 'Clifton 10',
            'category': 'running',
            'price': 149.99,
            'image_url': 'https://images.unsplash.com/photo-1606107557195-0e29a4b5b4aa?w=400',
            'affiliate_link': '#',
            'width_fit': 'wide',
            'arch_support': 'neutral',
            'weight_capacity': 'light',
            'best_for_activity': 'road_running',
            'cushioning': 'maximum',
            'footstrike_support': 'neutral',
            'distance_capacity': 'long',
            'carbon_plate': False,
            'best_for_distance': 'training',
            'gender': 'female'
        },
        {
            'brand': 'New Balance',
            'model': 'Fresh Foam X 880 v15',
            'category': 'running',
            'price': 144.99,
            'image_url': 'https://images.unsplash.com/photo-1605034313761-73ea4a0cfbf3?w=400',
            'affiliate_link': '#',
            'width_fit': 'standard',
            'arch_support': 'neutral',
            'weight_capacity': 'medium',
            'best_for_activity': 'road_running',
            'cushioning': 'maximum',
            'footstrike_support': 'neutral',
            'distance_capacity': 'medium',
            'carbon_plate': False,
            'best_for_distance': 'training',
            'gender': 'female'
        },
        {
            'brand': 'Brooks',
            'model': 'Glycerin 22',
            'category': 'running',
            'price': 159.99,
            'image_url': 'https://images.unsplash.com/photo-1600185365483-26d7a4cc7519?w=400',
            'affiliate_link': '#',
            'width_fit': 'standard',
            'arch_support': 'neutral',
            'weight_capacity': 'medium',
            'best_for_activity': 'road_running',
            'cushioning': 'maximum',
            'footstrike_support': 'neutral',
            'distance_capacity': 'long',
            'carbon_plate': False,
            'best_for_distance': 'long_run',
            'gender': 'female'
        },
        {
            'brand': 'Hoka',
            'model': 'Bondi 9',
            'category': 'running',
            'price': 169.99,
            'image_url': 'https://images.unsplash.com/photo-1606107557195-0e29a4b5b4aa?w=400',
            'affiliate_link': '#',
            'width_fit': 'wide',
            'arch_support': 'neutral',
            'weight_capacity': 'heavy',
            'best_for_activity': 'road_running',
            'cushioning': 'maximum',
            'footstrike_support': 'neutral',
            'distance_capacity': 'long',
            'carbon_plate': False,
            'best_for_distance': 'recovery',
            'gender': 'female'
        },
        # ==================== HOMBRES - ROAD RUNNING ESTABILIDAD/PRONACIÓN ====================
        {
            'brand': 'ASICS',
            'model': 'Gel-Kayano 32',
            'category': 'running',
            'price': 179.99,
            'image_url': 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=400',
            'affiliate_link': '#',
            'width_fit': 'standard',
            'arch_support': 'high',
            'weight_capacity': 'heavy',
            'best_for_activity': 'road_running',
            'cushioning': 'maximum',
            'footstrike_support': 'pronation',
            'distance_capacity': 'long',
            'carbon_plate': False,
            'best_for_distance': 'training',
            'gender': 'male'
        },
        {
            'brand': 'Puma',
            'model': 'ForeverRun Nitro 2',
            'category': 'running',
            'price': 134.99,
            'image_url': 'https://images.unsplash.com/photo-1549298916-b41d501d3772?w=400',
            'affiliate_link': '#',
            'width_fit': 'wide',
            'arch_support': 'medium',
            'weight_capacity': 'medium',
            'best_for_activity': 'road_running',
            'cushioning': 'medium',
            'footstrike_support': 'pronation',
            'distance_capacity': 'medium',
            'carbon_plate': False,
            'best_for_distance': 'training',
            'gender': 'male'
        },
        # ==================== ROAD RUNNING - COMPETICIÓN NEUTRA (UNISEX/MASC) ====================
        {
            'brand': 'Nike',
            'model': 'Vaporfly 4',
            'category': 'running',
            'price': 259.99,
            'image_url': 'https://images.unsplash.com/photo-1608231387042-66d1773070a5?w=400',
            'affiliate_link': '#',
            'width_fit': 'narrow',
            'arch_support': 'neutral',
            'weight_capacity': 'light',
            'best_for_activity': 'road_running',
            'cushioning': 'maximum',
            'footstrike_support': 'neutral',
            'distance_capacity': 'medium',
            'carbon_plate': True,
            'best_for_distance': 'half_marathon',
            'gender': 'unisex'
        },
        {
            'brand': 'Nike',
            'model': 'Alphafly 3',
            'category': 'running',
            'price': 289.99,
            'image_url': 'https://images.unsplash.com/photo-1608231387042-66d1773070a5?w=400',
            'affiliate_link': '#',
            'width_fit': 'narrow',
            'arch_support': 'neutral',
            'weight_capacity': 'light',
            'best_for_activity': 'road_running',
            'cushioning': 'maximum',
            'footstrike_support': 'neutral',
            'distance_capacity': 'long',
            'carbon_plate': True,
            'best_for_distance': 'marathon',
            'gender': 'male'
        },
        {
            'brand': 'Saucony',
            'model': 'Endorphin Elite 2',
            'category': 'running',
            'price': 274.99,
            'image_url': 'https://images.unsplash.com/photo-1608231387042-66d1773070a5?w=400',
            'affiliate_link': '#',
            'width_fit': 'standard',
            'arch_support': 'neutral',
            'weight_capacity': 'light',
            'best_for_activity': 'road_running',
            'cushioning': 'maximum',
            'footstrike_support': 'neutral',
            'distance_capacity': 'long',
            'carbon_plate': True,
            'best_for_distance': 'marathon',
            'gender': 'unisex'
        },
        # ==================== TRAIL RUNNING - NEUTRO (Corta/Media Distancia) ====================
        {
            'brand': 'Saucony',
            'model': 'Peregrine 15',
            'category': 'running',
            'price': 139.99,
            'image_url': 'https://images.unsplash.com/photo-1544966503-7cc5ac882d5b?w=400',
            'affiliate_link': '#',
            'width_fit': 'standard',
            'arch_support': 'neutral',
            'weight_capacity': 'medium',
            'best_for_activity': 'trail_running',
            'cushioning': 'medium',
            'footstrike_support': 'neutral',
            'distance_capacity': 'medium',
            'carbon_plate': False,
            'best_for_distance': 'half_marathon',
            'gender': 'male'
        },
        {
            'brand': 'Hoka',
            'model': 'Torrent 4',
            'category': 'running',
            'price': 129.99,
            'image_url': 'https://images.unsplash.com/photo-1544966503-7cc5ac882d5b?w=400',
            'affiliate_link': '#',
            'width_fit': 'standard',
            'arch_support': 'neutral',
            'weight_capacity': 'light',
            'best_for_activity': 'trail_running',
            'cushioning': 'medium',
            'footstrike_support': 'neutral',
            'distance_capacity': 'medium',
            'carbon_plate': False,
            'best_for_distance': 'half_marathon',
            'gender': 'male'
        },
        {
            'brand': 'Hoka',
            'model': 'Zinal 2',
            'category': 'running',
            'price': 144.99,
            'image_url': 'https://images.unsplash.com/photo-1544966503-7cc5ac882d5b?w=400',
            'affiliate_link': '#',
            'width_fit': 'standard',
            'arch_support': 'neutral',
            'weight_capacity': 'light',
            'best_for_activity': 'trail_running',
            'cushioning': 'medium',
            'footstrike_support': 'neutral',
            'distance_capacity': 'short',
            'carbon_plate': False,
            'best_for_distance': '10k',
            'gender': 'male'
        },
        {
            'brand': 'Adidas',
            'model': 'Terrex Speed Flow',
            'category': 'running',
            'price': 119.99,
            'image_url': 'https://images.unsplash.com/photo-1544966503-7cc5ac882d5b?w=400',
            'affiliate_link': '#',
            'width_fit': 'standard',
            'arch_support': 'neutral',
            'weight_capacity': 'light',
            'best_for_activity': 'trail_running',
            'cushioning': 'medium',
            'footstrike_support': 'neutral',
            'distance_capacity': 'short',
            'carbon_plate': False,
            'best_for_distance': '10k',
            'gender': 'male'
        },
        {
            'brand': 'NNormal',
            'model': 'Kjerag',
            'category': 'running',
            'price': 169.99,
            'image_url': 'https://images.unsplash.com/photo-1544966503-7cc5ac882d5b?w=400',
            'affiliate_link': '#',
            'width_fit': 'narrow',
            'arch_support': 'neutral',
            'weight_capacity': 'light',
            'best_for_activity': 'trail_running',
            'cushioning': 'minimal',
            'footstrike_support': 'neutral',
            'distance_capacity': 'short',
            'carbon_plate': False,
            'best_for_distance': '10k',
            'gender': 'male'
        },
        # ==================== TRAIL RUNNING - NEUTRO (Media/Larga Distancia) ====================
        {
            'brand': 'Hoka',
            'model': 'Speedgoat 6',
            'category': 'running',
            'price': 159.99,
            'image_url': 'https://images.unsplash.com/photo-1544966503-7cc5ac882d5b?w=400',
            'affiliate_link': '#',
            'width_fit': 'standard',
            'arch_support': 'neutral',
            'weight_capacity': 'medium',
            'best_for_activity': 'trail_running',
            'cushioning': 'maximum',
            'footstrike_support': 'neutral',
            'distance_capacity': 'long',
            'carbon_plate': False,
            'best_for_distance': 'ultra',
            'gender': 'male'
        },
        {
            'brand': 'Salomon',
            'model': 'Speedcross 6',
            'category': 'running',
            'price': 149.99,
            'image_url': 'https://images.unsplash.com/photo-1544966503-7cc5ac882d5b?w=400',
            'affiliate_link': '#',
            'width_fit': 'narrow',
            'arch_support': 'neutral',
            'weight_capacity': 'medium',
            'best_for_activity': 'trail_running',
            'cushioning': 'medium',
            'footstrike_support': 'neutral',
            'distance_capacity': 'medium',
            'carbon_plate': False,
            'best_for_distance': 'half_marathon',
            'gender': 'male'
        },
        {
            'brand': 'Saucony',
            'model': 'Xodus Ultra 4',
            'category': 'running',
            'price': 169.99,
            'image_url': 'https://images.unsplash.com/photo-1544966503-7cc5ac882d5b?w=400',
            'affiliate_link': '#',
            'width_fit': 'wide',
            'arch_support': 'neutral',
            'weight_capacity': 'medium',
            'best_for_activity': 'trail_running',
            'cushioning': 'maximum',
            'footstrike_support': 'neutral',
            'distance_capacity': 'ultra',
            'carbon_plate': False,
            'best_for_distance': 'ultra',
            'gender': 'male'
        },
        {
            'brand': 'New Balance',
            'model': 'Hierro v9',
            'category': 'running',
            'price': 139.99,
            'image_url': 'https://images.unsplash.com/photo-1544966503-7cc5ac882d5b?w=400',
            'affiliate_link': '#',
            'width_fit': 'standard',
            'arch_support': 'neutral',
            'weight_capacity': 'medium',
            'best_for_activity': 'trail_running',
            'cushioning': 'maximum',
            'footstrike_support': 'neutral',
            'distance_capacity': 'medium',
            'carbon_plate': False,
            'best_for_distance': 'half_marathon',
            'gender': 'male'
        },
        {
            'brand': 'Brooks',
            'model': 'Cascadia 19',
            'category': 'running',
            'price': 144.99,
            'image_url': 'https://images.unsplash.com/photo-1544966503-7cc5ac882d5b?w=400',
            'affiliate_link': '#',
            'width_fit': 'standard',
            'arch_support': 'neutral',
            'weight_capacity': 'medium',
            'best_for_activity': 'trail_running',
            'cushioning': 'medium',
            'footstrike_support': 'neutral',
            'distance_capacity': 'long',
            'carbon_plate': False,
            'best_for_distance': 'ultra',
            'gender': 'male'
        },
        {
            'brand': 'Hoka',
            'model': 'Mafate X',
            'category': 'running',
            'price': 199.99,
            'image_url': 'https://images.unsplash.com/photo-1544966503-7cc5ac882d5b?w=400',
            'affiliate_link': '#',
            'width_fit': 'standard',
            'arch_support': 'neutral',
            'weight_capacity': 'medium',
            'best_for_activity': 'trail_running',
            'cushioning': 'maximum',
            'footstrike_support': 'neutral',
            'distance_capacity': 'ultra',
            'carbon_plate': True,
            'best_for_distance': 'ultra',
            'gender': 'male'
        },
        # ==================== TRAIL RUNNING - MUJER (Modelos Específicos) ====================
        {
            'brand': 'Hoka',
            'model': 'Torrent 4',
            'category': 'running',
            'price': 129.99,
            'image_url': 'https://images.unsplash.com/photo-1544966503-7cc5ac882d5b?w=400',
            'affiliate_link': '#',
            'width_fit': 'standard',
            'arch_support': 'neutral',
            'weight_capacity': 'light',
            'best_for_activity': 'trail_running',
            'cushioning': 'medium',
            'footstrike_support': 'neutral',
            'distance_capacity': 'medium',
            'carbon_plate': False,
            'best_for_distance': 'half_marathon',
            'gender': 'female'
        },
        {
            'brand': 'La Sportiva',
            'model': 'Bushido III',
            'category': 'running',
            'price': 154.99,
            'image_url': 'https://images.unsplash.com/photo-1544966503-7cc5ac882d5b?w=400',
            'affiliate_link': '#',
            'width_fit': 'narrow',
            'arch_support': 'neutral',
            'weight_capacity': 'medium',
            'best_for_activity': 'trail_running',
            'cushioning': 'medium',
            'footstrike_support': 'neutral',
            'distance_capacity': 'medium',
            'carbon_plate': False,
            'best_for_distance': 'half_marathon',
            'gender': 'female'
        },
        {
            'brand': 'Brooks',
            'model': 'Caldera 8',
            'category': 'running',
            'price': 164.99,
            'image_url': 'https://images.unsplash.com/photo-1544966503-7cc5ac882d5b?w=400',
            'affiliate_link': '#',
            'width_fit': 'wide',
            'arch_support': 'neutral',
            'weight_capacity': 'medium',
            'best_for_activity': 'trail_running',
            'cushioning': 'maximum',
            'footstrike_support': 'neutral',
            'distance_capacity': 'long',
            'carbon_plate': False,
            'best_for_distance': 'ultra',
            'gender': 'female'
        },
        # ==================== TRAIL RUNNING - TRANSICIÓN/CAMINOS (Unisex) ====================
        {
            'brand': 'Nike',
            'model': 'Pegasus Trail 5',
            'category': 'running',
            'price': 139.99,
            'image_url': 'https://images.unsplash.com/photo-1544966503-7cc5ac882d5b?w=400',
            'affiliate_link': '#',
            'width_fit': 'standard',
            'arch_support': 'neutral',
            'weight_capacity': 'medium',
            'best_for_activity': 'trail_running',
            'cushioning': 'medium',
            'footstrike_support': 'neutral',
            'distance_capacity': 'medium',
            'carbon_plate': False,
            'best_for_distance': 'training',
            'gender': 'unisex'
        },
        {
            'brand': 'Hoka',
            'model': 'Challenger 8',
            'category': 'running',
            'price': 134.99,
            'image_url': 'https://images.unsplash.com/photo-1544966503-7cc5ac882d5b?w=400',
            'affiliate_link': '#',
            'width_fit': 'wide',
            'arch_support': 'neutral',
            'weight_capacity': 'medium',
            'best_for_activity': 'trail_running',
            'cushioning': 'medium',
            'footstrike_support': 'neutral',
            'distance_capacity': 'medium',
            'carbon_plate': False,
            'best_for_distance': 'training',
            'gender': 'unisex'
        },
        {
            'brand': 'Altra',
            'model': 'Lone Peak 9',
            'category': 'running',
            'price': 144.99,
            'image_url': 'https://images.unsplash.com/photo-1544966503-7cc5ac882d5b?w=400',
            'affiliate_link': '#',
            'width_fit': 'wide',
            'arch_support': 'neutral',
            'weight_capacity': 'medium',
            'best_for_activity': 'trail_running',
            'cushioning': 'medium',
            'footstrike_support': 'neutral',
            'distance_capacity': 'long',
            'carbon_plate': False,
            'best_for_distance': 'ultra',
            'gender': 'unisex'
        },
        {
            'brand': 'Topo Athletic',
            'model': 'Ultraventure 4',
            'category': 'running',
            'price': 149.99,
            'image_url': 'https://images.unsplash.com/photo-1544966503-7cc5ac882d5b?w=400',
            'affiliate_link': '#',
            'width_fit': 'wide',
            'arch_support': 'neutral',
            'weight_capacity': 'medium',
            'best_for_activity': 'trail_running',
            'cushioning': 'maximum',
            'footstrike_support': 'neutral',
            'distance_capacity': 'long',
            'carbon_plate': False,
            'best_for_distance': 'ultra',
            'gender': 'unisex'
        },
    ]
    return sample_shoes